### ISSUE TITLE
Girls Style: Paesyeon Lideo Seon-eon! (KOR) save support

### ISSUE THREAD

**Issue by RocketRobz** [RocketRobz/SavvyManager#5]
The title ID for this game is not known, so the save data cannot be edited yet.
If any of you have a copy of this game, please dump the game as a CXI file using GodMode9, then place it in your Citra ROMs folder, and start up Citra.
Make sure `Title ID` is set for `Row 2` in the Citra UI settings.

After doing all that, please show a screenshot of the Citra ROM list, featuring the game's icon.

**Comment by hax0kartik** [comment]
![image](https://user-images.githubusercontent.com/16360444/92438519-9c84f800-f1c6-11ea-9425-9812ad9c74cc.png)
Hope this helps :)

**Comment by RocketRobz** [comment]
Thank you! I never knew about this site.
