### ISSUE TITLE
SS Styling Star (New Style Boutique 3) save not recognized

### ISSUE THREAD

**Issue by subworx** [RocketRobz/SavvyManager#7]
- New 2DS XL, 11.14.0-46, Luma 10.2.1
- SavvyManager Thanksgiving 2020 Release, CIA version
- Style Savvy Styling Star USA version (00040000001C2500) with saved game.

I went through the first job and as soon as saving was possible, I saved.
SavvyManager claims it cannot find the savegame.

JKSV Screenshot (list of games whited out) showing game name and ID
![01](https://user-images.githubusercontent.com/10171215/121607889-26f9d100-ca51-11eb-8409-5e9c8ac38612.png)

Failure to open Save Data. Dumping Ext Data works.
![02](https://user-images.githubusercontent.com/10171215/121607890-27926780-ca51-11eb-89fc-3df75e013f81.png)

SavvyManager error message
![04](https://user-images.githubusercontent.com/10171215/121607893-282afe00-ca51-11eb-8de6-bf7c7e28e2e1.png)

The whole data is there and can be dumped, just not in Save but in External instead. Proof:
![05](https://user-images.githubusercontent.com/10171215/121608277-e2bb0080-ca51-11eb-8775-7366467972bd.png)

Thank your for looking into this :)

**Comment by RocketRobz** [comment]
If the console region doesn't match that of the game or save data, you'll get that message.

**Comment by subworx** [comment]
Sad to hear, but good to know. Thank you very much :)
